export const API_URL = process.env.NEXT_PUBLIC_API_URL;
export const MEDIA_URL = process.env.NEXT_PUBLIC_MEDIA_URL;
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL;

export const GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;

export const RZP_TEST_KEY_ID = process.env.NEXT_PUBLIC_RZP_TEST_KEY_ID;

export const PREMIUM_PLAN_PRICE_INR_MONTHLY =
  process.env.NEXT_PUBLIC_PREMIUM_PLAN_PRICE_INR_MONTHLY;

export const PREMIUM_PLAN_PRICE_INR_YEARLY =
  process.env.NEXT_PUBLIC_PREMIUM_PLAN_PRICE_INR_YEARLY;

export const PREMIUM_PLAN_PRICE_USD_MONTHLY =
  process.env.NEXT_PUBLIC_PREMIUM_PLAN_PRICE_USD_MONTHLY;

export const PREMIUM_PLAN_PRICE_USD_YEARLY =
  process.env.NEXT_PUBLIC_PREMIUM_PLAN_PRICE_USD_YEARLY;
